eprintfn @".__                                   .__                     _____    _  _   "
eprintfn @"|  |    ____  _____   _______   ____  |__|  ____     ____   _/ ____\__| || |__"
eprintfn @"|  |  _/ __ \ \__  \  \_  __ \ /    \ |  | /    \   / ___\  \   __\ \   __   /"
eprintfn @"|  |__\  ___/  / __ \_ |  | \/|   |  \|  ||   |  \ / /_/  >  |  |    |  ||  | "
eprintfn @"|____/ \___  >(____  / |__|   |___|  /|__||___|  / \___  /   |__|   /_  ~~  _\"
eprintfn @"           \/      \/              \/          \/ /_____/             |_||_|  "
eprintfn @"         .__   __   .__     "
eprintfn @"__  _  __|__|_/  |_ |  |__  "
eprintfn @"\ \/ \/ /|  |\   __\|  |  \ "
eprintfn @" \     / |  | |  |  |   Y  \"
eprintfn @"  \/\_/  |__| |__|  |___|  /"
eprintfn @"                         \/ "
eprintfn @"  _____ .__   .__                          "
eprintfn @"_/ ____\|  |  |__|  ____     ____    ______"
eprintfn @"\   __\ |  |  |  | /    \   / ___\  /  ___/"
eprintfn @" |  |   |  |__|  ||   |  \ / /_/  > \___ \ "
eprintfn @" |__|   |____/|__||___|  / \___  / /____  >"
eprintfn @"                       \/ /_____/       \/ "

let main =
    // TODO: add '!' after "world" in the below string
    printfn "Hello, world"
